/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Numerology;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class NumerologyTest {
    @Test 
    public void testSomeLibraryMethod() {
        Numerology classUnderTest = new Numerology();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    
    public class Numerology {
    	public boolean someLibraryMethod() {
            return true;
        }
    }
}
