/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numerology;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import numerology.rules.RuleInterface;
import numerology.rules.NoRule;
import numerology.rules.RuleReplaceFour;
import numerology.rules.RuleReplaceNineForTens;
import numerology.rules.RuleReplaceSixsForThrees;
import numerology.rules.RuleReplaceThree;
import numerology.rules.RuleReplaceTwosForOnes;
import numerology.rules.RuleSevenResetsRuleThreeAndFour;

public class Numerology {
	
	public List<RuleInterface> rules = 
			Arrays.asList(
					new NoRule(), 
					new NoRule(), 
					new RuleReplaceTwosForOnes(),
					new RuleReplaceThree(),
					new RuleReplaceFour(),
					new NoRule(),
					new RuleReplaceSixsForThrees(),
					new RuleSevenResetsRuleThreeAndFour(),
					new NoRule(),
					new RuleReplaceNineForTens()
			);
	
	public List<Integer> generateOutput(List<Integer> input) {
    	Memory.threesReplaced = 0;
    	Memory.foursReplaced = 0;
    	
		List<Integer> output = new ArrayList<Integer>();
		for (int i = 0; i< input.size(); i++) {
			if (input.get(i) < 10) {
				output.addAll(rules.get(input.get(i)).applyRule(input, i));
			} else {
				output.addAll(new NoRule().applyRule(input, i));
			}
		}
		if (input.get(0) % 2 != 0 && output.get(output.size()-1) % 2 == 0) {
			output.set(output.size()-1, output.get(output.size()-1)-1);
		}
		if (input.get(0) % 2 == 0 && output.get(output.size()-1) % 2 != 0) {
			output.set(output.size()-1, output.get(output.size()-1)+1);
		}
		return output;
	}
}
